### PR TITLE
https://github.com/TimonKK/clickhouse/issues/128

### PR DESCRIPTION
**Pull request by SEA99**
"data.every is not a function" error

### CODE REVIEW

**Comment by SEA99** [comment]
added commit for issue 124

**Comment by TimonKK** [comment]
Could you add some test for your changes?

**Comment by SEA99** [comment]
I can add to existing one

**Comment by SEA99** [comment]
done

**Comment by SEA99** [comment]
also added possibility to run test with connect configuration. You can create test_config.json in root directory of project and fill like {
    "url":"111.222.111.222",
    "port":8123,
    "basicAuth": {
      "username": "default",
      "password": "xxxxxxx"
    }
}

**Pull request merged**
