### PR TITLE
added insert query format check case

### PR DESCRIPTION
**Pull request by pavhov**
check this case in query

### CODE REVIEW

**Comment by TimonKK** [comment]
Hi, thanks for PR.
Can you show code example, which had need for this changes?
Test failed with with changes http://prntscr.com/p6e6uw

**Comment by pavhov** [comment]
Sorry for late answer Timon
I want to create tsv, csv snd json parsers for this package.
I’ve already completed csv parsing case. Now I’m trying to complete tcv parsing case.
In package I must add one `format` option, 
```
const clickhouse = new ClickHouse({
	...
        format: "json", // "json" || "csv" || "tsv"
});
```

but in case of format json or [Formats for Input and Output Data](https://clickhouse.yandex/docs/en/interfaces/formats/) exists in query this format option should be ignored. (edited)

**Comment by TimonKK** [comment]
You can't change format so easy. If you set not **JSON** format, therea are need change stream parser [here ](https://github.com/TimonKK/clickhouse/blob/0a4c2a2bf7f3f7135b0c6429e3ea3dc68b409c9a/index.js#L313) and [here](https://github.com/TimonKK/clickhouse/blob/0a4c2a2bf7f3f7135b0c6429e3ea3dc68b409c9a/index.js#L161)

**Comment by pavhov** [comment]
Hello Timon thanks for help
I’ve created parsers for CSV and TSV formats, but streaming query cases not ready yet. 
I will finish it in this days.

**Comment by pavhov** [comment]
image

all tests are 24 passing in (1m)

**Comment by TimonKK** [comment]
Could you pleace write some test for stream and insert with new format?

**Comment by pavhov** [comment]
Yes Timon I will write tests for stream

**Pull request merged**
