### PR TITLE
#75: Add raw return type

### PR DESCRIPTION
**Pull request by beglex**
see #75

### CODE REVIEW

**Comment by TimonKK** [comment]
Hello. Could you please add test for your change and upgrae version in package.json?

**Comment by beglex** [comment]
Tests are added
Update as a minor or patch version?

**Comment by TimonKK** [comment]
Thanks. I think it is minor change

**Comment by beglex** [comment]
Done!
Via command `npm version minor`, so *version* in package.json differs from the old one

**Pull request merged**
