### PR TITLE
support query long sql

### PR DESCRIPTION
**Pull request by CherryCHan**
if query is too long to request, use post formdata to transfer it. And remove comments or multiple whitespaces.

### CODE REVIEW

**Comment by TimonKK** [comment]
Hello. Could you please wrap this action in option in settings? Like
```javascript
clickhouse = new ClickHouse({
    trimQuery: true
});
```

**Comment by CherryCHan** [comment]
> Hello. Could you please wrap this action in option in settings? Like
> 
> ```js
> clickhouse = new ClickHouse({
>     trimQuery: true
> });
> ```

**Comment by CherryCHan** [comment]
can developer set using post or set removing comments ? or both ?

**Comment by TimonKK** [comment]
I think `trimQuery` for removing comment and `usePost` for post

**Comment by CherryCHan** [comment]
thanks for replying. I have edited in pull request #85

**Comment by mike-luabase** [comment]
@TimonKK is this going to be merged? You get errors if there are leading or trailing comments in a query currently, e.g.

```
-- some comment
select 1
```

**Comment by mike-luabase** [comment]
Also, you need to trim again after the comment replacement (currently this leave a space at the start if the query starts with a comment)

```
query = query.trim().trimEnd().replace(/(--[^\n]*)/g, '').replace(/\s+/g, ' ').replace(/;$/gm, '').trim().trimEnd()
```

**Comment by TimonKK** [comment]
Could you please add some tests for your changes?

**Pull request merged**
