### PR TITLE
add nullable type support

### PR DESCRIPTION
**Pull request by mjodeh**
nullable type support is added to support column types such as Nullable(String)

### CODE REVIEW

**Comment by TimonKK** [comment]
Это изменения ломают тесты и логику запросов. Можете расписать в чем смысл изменений?

**Comment by mjodeh** [comment]
when the value is undefined and you check its `typeof` you get `"undefined"` which does not match any of the used cases https://github.com/TimonKK/clickhouse/blob/e33eee64813fb1d6361beb82ffdd6e0934b89a8e/index.js#L165 that's why I added a check so if the value is undefined then attach escape null and return.
This is helpful when there are nullable columns in the table which is usual use case for clickhouse, have a look at https://github.com/TimonKK/clickhouse/issues/43

**Comment by TimonKK** [comment]
Your changes broke tests

**Comment by TimonKK** [comment]
Your changes broke tests http://prntscr.com/uwpnmz

**Pull request closed without merging**
